### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by iongion** [9elements/academy-webdev-bootstrap#7]
` webpack-notifier` is missing from package.json and is required by `gulp build`

```
gulp build
module.js:338
    throw err;
    ^
Error: Cannot find module 'webpack-notifier'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (gulp/config.js:3:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by Lionardo** [comment]
Could you please add this to package.json 


```json
"webpack-notifier":"^1.2.1"
```

thx
